name: Building PBRP

on:
  workflow_dispatch:
    inputs:
      TagDetail:
        name:''
        body:''

env:
  TARGET: pbrp

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Cleaning Up Runner
         uses: rokibhasansagar/slimhub_actions@main

       - name: Auto Adapt Manifest
         run: echo "MANIFEST=https://github.com/PitchBlackRecoveryProject/manifest_pb -b ${GITHUB_REF##*/}" >> $GITHUB_ENV
            
       - name: Recovery Compilation
         uses: PitchBlackRecoveryProject/Recovery-Compiler@production
 
       - name: Create Release
         id: create_release
         uses: actions/create-release@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag_name: ${{ github.event.inputs.TagDetail.name }}
           release_name: Release ${{ github.event.inputs.TagDetail.name }}
           body: ${{ github.event.inputs.TagDetail.body }}
           draft: false
           prerelease: false
           
       - name: Upload Release Asset
         id: upload-release-asset 
         uses: xresloader/upload-to-github-release@master
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           file: "${BuildPath}/out/target/product/${CODENAME}/*{.img,.zip}"
           release_id: ${{ steps.create_release.outputs.id }}
           overwrite: true
           verbose: true
